['SalesKaggle3.csv']
(146, 14)
*****************
Order               146
File_Type             2
SKU_number          146
SoldFlag              2
SoldCount             6
MarketingType         2
ReleaseNumber        71
New_Release_Flag      2
StrengthFactor      146
PriceReg            105
ReleaseYear          85
ItemCount            60
LowUserPrice        118
LowNetPrice         136
dtype: int64
*****************
124
22





(99, 8) (99,)
(25, 8) (25,)
Class 0 numbers:  72
Class 1 numbers:  27
Traceback (most recent call last):
  File "kernele7f4dbb964.py", line 299, in <module>
    sm = SMOTE(random_state=12, ratio = 1.0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/imblearn/utils/_validation.py", line 640, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'ratio'
[Try Solution]: OrderedDict([('API', 'imblearn.over_sampling.SMOTE'), ('action', 'arg_delete'), ('from_name', 'ratio'), ('to_name', '*')])['SalesKaggle3.csv']
(146, 14)
*****************
Order               146
File_Type             2
SKU_number          146
SoldFlag              2
SoldCount             6
MarketingType         2
ReleaseNumber        71
New_Release_Flag      2
StrengthFactor      146
PriceReg            105
ReleaseYear          85
ItemCount            60
LowUserPrice        118
LowNetPrice         136
dtype: int64
*****************
124
22





(99, 8) (99,)
(25, 8) (25,)
Class 0 numbers:  74
Class 1 numbers:  25
Class 0 numbers:  68
Class 1 numbers:  68
Validation Results
0.6
0.0

Test Results
0.8
0.5

ROC AUC score
0.6973684210526315
Confusion matrix, without normalization
[[17  2]
 [ 3  3]]

Normalized confusion matrix
[[0.89 0.11]
 [0.5  0.5 ]]



[REPAIR EXEC TIME]: 6.244275808334351['SalesKaggle3.csv']
(146, 14)
*****************
Order               146
File_Type             2
SKU_number          146
SoldFlag              2
SoldCount             6
MarketingType         2
ReleaseNumber        71
New_Release_Flag      2
StrengthFactor      146
PriceReg            105
ReleaseYear          85
ItemCount            60
LowUserPrice        118
LowNetPrice         136
dtype: int64
*****************
124
22





(99, 8) (99,)
(25, 8) (25,)
Class 0 numbers:  75
Class 1 numbers:  24
Traceback (most recent call last):
  File "kernele7f4dbb964.py", line 299, in <module>
    sm = SMOTE(random_state=12, ratio = 1.0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/imblearn/utils/_validation.py", line 640, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'ratio'
[Try Solution]: OrderedDict([('API', 'imblearn.over_sampling.SMOTE'), ('action', 'arg_delete'), ('from_name', 'ratio'), ('to_name', '*')])['SalesKaggle3.csv']
(146, 14)
*****************
Order               146
File_Type             2
SKU_number          146
SoldFlag              2
SoldCount             6
MarketingType         2
ReleaseNumber        71
New_Release_Flag      2
StrengthFactor      146
PriceReg            105
ReleaseYear          85
ItemCount            60
LowUserPrice        118
LowNetPrice         136
dtype: int64
*****************
124
22





(99, 8) (99,)
(25, 8) (25,)
Class 0 numbers:  74
Class 1 numbers:  25
Class 0 numbers:  66
Class 1 numbers:  66
Validation Results
0.8
0.5

Test Results
0.72
0.3333333333333333

ROC AUC score
0.587719298245614
Confusion matrix, without normalization
[[16  3]
 [ 4  2]]

Normalized confusion matrix
[[0.84 0.16]
 [0.67 0.33]]



[REPAIR EXEC TIME]: 8.59458589553833['SalesKaggle3.csv']
(146, 14)
*****************
Order               146
File_Type             2
SKU_number          146
SoldFlag              2
SoldCount             6
MarketingType         2
ReleaseNumber        71
New_Release_Flag      2
StrengthFactor      146
PriceReg            105
ReleaseYear          85
ItemCount            60
LowUserPrice        118
LowNetPrice         136
dtype: int64
*****************
124
22





(99, 8) (99,)
(25, 8) (25,)
Class 0 numbers:  75
Class 1 numbers:  24
Traceback (most recent call last):
  File "kernele7f4dbb964.py", line 299, in <module>
    sm = SMOTE(random_state=12, ratio = 1.0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/imblearn/utils/_validation.py", line 640, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'ratio'
[Try Solution]: OrderedDict([('API', 'imblearn.over_sampling.SMOTE'), ('action', 'arg_delete'), ('from_name', 'ratio'), ('to_name', '*')])['SalesKaggle3.csv']
(146, 14)
*****************
Order               146
File_Type             2
SKU_number          146
SoldFlag              2
SoldCount             6
MarketingType         2
ReleaseNumber        71
New_Release_Flag      2
StrengthFactor      146
PriceReg            105
ReleaseYear          85
ItemCount            60
LowUserPrice        118
LowNetPrice         136
dtype: int64
*****************
124
22





(99, 8) (99,)
(25, 8) (25,)
Class 0 numbers:  78
Class 1 numbers:  21
Class 0 numbers:  73
Class 1 numbers:  73
Validation Results
0.6
0.2

Test Results
0.68
0.5

ROC AUC score
0.6500000000000001
Confusion matrix, without normalization
[[12  3]
 [ 5  5]]

Normalized confusion matrix
[[0.8 0.2]
 [0.5 0.5]]



[REPAIR EXEC TIME]: 6.5170676708221436