/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
['Fish.csv']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB
  Species  Length1  Length2  Length3   Height   Width
0   Bream     23.2     25.4     30.0  11.5200  4.0200
1   Bream     24.0     26.3     31.2  12.4800  4.3056
2   Bream     23.9     26.5     31.1  12.3778  4.6961
3   Bream     26.3     29.0     33.5  12.7300  4.4555
4   Bream     26.5     29.0     34.0  12.4440  5.1340
0    242.0
1    290.0
2    340.0
3    363.0
4    430.0
Name: Weight, dtype: float64
Traceback (most recent call last):
  File "weight-prediction.py", line 101, in <module>
    hot_encoder = OneHotEncoder(categorical_features = [0])
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[REPAIR EXEC TIME]: 1.7923381328582764/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
['Fish.csv']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB
  Species  Length1  Length2  Length3   Height   Width
0   Bream     23.2     25.4     30.0  11.5200  4.0200
1   Bream     24.0     26.3     31.2  12.4800  4.3056
2   Bream     23.9     26.5     31.1  12.3778  4.6961
3   Bream     26.3     29.0     33.5  12.7300  4.4555
4   Bream     26.5     29.0     34.0  12.4440  5.1340
0    242.0
1    290.0
2    340.0
3    363.0
4    430.0
Name: Weight, dtype: float64
Traceback (most recent call last):
  File "weight-prediction.py", line 101, in <module>
    hot_encoder = OneHotEncoder(categorical_features = [0])
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[REPAIR EXEC TIME]: 1.7404875755310059/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
['Fish.csv']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB
  Species  Length1  Length2  Length3   Height   Width
0   Bream     23.2     25.4     30.0  11.5200  4.0200
1   Bream     24.0     26.3     31.2  12.4800  4.3056
2   Bream     23.9     26.5     31.1  12.3778  4.6961
3   Bream     26.3     29.0     33.5  12.7300  4.4555
4   Bream     26.5     29.0     34.0  12.4440  5.1340
0    242.0
1    290.0
2    340.0
3    363.0
4    430.0
Name: Weight, dtype: float64
Traceback (most recent call last):
  File "weight-prediction.py", line 101, in <module>
    hot_encoder = OneHotEncoder(categorical_features = [0])
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[REPAIR EXEC TIME]: 1.6918768882751465