Traceback (most recent call last):
  File "bank-customer-churn-mlp-with-keras.py", line 42, in <module>
    one_hot_encoder = OneHotEncoder(categorical_features=[shift])
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[REPAIR EXEC TIME]: 0.9902877807617188Traceback (most recent call last):
  File "bank-customer-churn-mlp-with-keras.py", line 42, in <module>
    one_hot_encoder = OneHotEncoder(categorical_features=[shift])
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[REPAIR EXEC TIME]: 1.027696132659912Traceback (most recent call last):
  File "bank-customer-churn-mlp-with-keras.py", line 42, in <module>
    one_hot_encoder = OneHotEncoder(categorical_features=[shift])
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[REPAIR EXEC TIME]: 1.0076112747192383