Traceback (most recent call last):
  File "attrition-using-linear-discriminant-analysis.py", line 212, in <module>
    from sklearn.cross_validation import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_validation'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.model_selection'), ('line_no', 212)])              precision    recall  f1-score   support

           0       0.90      0.96      0.93       371
           1       0.70      0.46      0.55        70

    accuracy                           0.88       441
   macro avg       0.80      0.71      0.74       441
weighted avg       0.87      0.88      0.87       441

[ True False  True False  True  True False  True False  True False False
  True  True False False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True]
[ 1  8  1  5  1  1  7  1  6  1  9 10  1  1  3  2  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  4  1  1  1  1  1  1  1  1  1  1  1  1  1
  1]
              precision    recall  f1-score   support

           0       0.91      0.96      0.93       371
           1       0.71      0.49      0.58        70

    accuracy                           0.89       441
   macro avg       0.81      0.72      0.76       441
weighted avg       0.88      0.89      0.88       441

              precision    recall  f1-score   support

           0       0.96      0.19      0.31       371
           1       0.18      0.96      0.31        70

    accuracy                           0.31       441
   macro avg       0.57      0.57      0.31       441
weighted avg       0.84      0.31      0.31       441

[REPAIR EXEC TIME]: 2.6368069648742676Traceback (most recent call last):
  File "attrition-using-linear-discriminant-analysis.py", line 212, in <module>
    from sklearn.cross_validation import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_validation'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.model_selection'), ('line_no', 212)])              precision    recall  f1-score   support

           0       0.90      0.96      0.93       371
           1       0.70      0.46      0.55        70

    accuracy                           0.88       441
   macro avg       0.80      0.71      0.74       441
weighted avg       0.87      0.88      0.87       441

[ True False  True False  True  True False  True False  True False False
  True  True False False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True]
[ 1  8  1  5  1  1  7  1  6  1  9 10  1  1  3  2  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  4  1  1  1  1  1  1  1  1  1  1  1  1  1
  1]
              precision    recall  f1-score   support

           0       0.91      0.96      0.93       371
           1       0.71      0.49      0.58        70

    accuracy                           0.89       441
   macro avg       0.81      0.72      0.76       441
weighted avg       0.88      0.89      0.88       441

              precision    recall  f1-score   support

           0       0.96      0.19      0.31       371
           1       0.18      0.96      0.31        70

    accuracy                           0.31       441
   macro avg       0.57      0.57      0.31       441
weighted avg       0.84      0.31      0.31       441

[REPAIR EXEC TIME]: 2.664391040802002