['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 109, in <module>
    from sklearn.preprocessing import Imputer
ImportError: cannot import name 'Imputer'
[Try Solution]: OrderedDict([('old_fqn', 'sklearn.preprocessing.Imputer'), ('new_fqn', 'sklearn.impute.SimpleImputer'), ('line_no', 109)])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 111, in <module>
    imputerHumidity=SimpleImputer(missing_values='NaN',strategy='mean',axis=0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_delete'), ('from_name', 'axis'), ('to_name', '*')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'number')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'string')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'np.nan')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 115, in <module>
    imputerTemperature=SimpleImputer(missing_values='NaN',strategy='mean',axis=0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_delete'), ('from_name', 'axis'), ('to_name', '*')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 116, in <module>
    imputerTemperature=imputerTemperature.fit(temperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'number')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 116, in <module>
    imputerTemperature=imputerTemperature.fit(temperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'string')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 116, in <module>
    imputerTemperature=imputerTemperature.fit(temperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'np.nan')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 120, in <module>
    imputerappTemp=SimpleImputer(missing_values='NaN',strategy='mean',axis=0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_delete'), ('from_name', 'axis'), ('to_name', '*')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 121, in <module>
    imputerappTemp=imputerappTemp.fit(apparentTemperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'number')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 121, in <module>
    imputerappTemp=imputerappTemp.fit(apparentTemperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'string')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 121, in <module>
    imputerappTemp=imputerappTemp.fit(apparentTemperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'np.nan')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 130, in <module>
    from sklearn.cross_validation import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_validation'
[Try Solution]: OrderedDict([('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.model_selection'), ('line_no', 130)])['weatherHistory.csv']
42.947044456379054


62.247405822478356


[REPAIR EXEC TIME]: 29.486547708511353['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 109, in <module>
    from sklearn.preprocessing import Imputer
ImportError: cannot import name 'Imputer'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.preprocessing.Imputer'), ('new_fqn', 'sklearn.impute.SimpleImputer'), ('line_no', 109)])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 111, in <module>
    imputerHumidity=SimpleImputer(missing_values='NaN',strategy='mean',axis=0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'
[REPAIR EXEC TIME]: 3.074692964553833['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 109, in <module>
    from sklearn.preprocessing import Imputer
ImportError: cannot import name 'Imputer'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.preprocessing.Imputer'), ('new_fqn', 'sklearn.impute.SimpleImputer'), ('line_no', 109)])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 111, in <module>
    imputerHumidity=SimpleImputer(missing_values='NaN',strategy='mean',axis=0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_delete'), ('from_name', 'axis'), ('to_name', '*')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_rename'), ('from_name', 'axis'), ('to_name', 'fill_values')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 111, in <module>
    imputerHumidity=SimpleImputer(missing_values='NaN',strategy='mean',fill_values=0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'fill_values'
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_rename'), ('from_name', 'axis'), ('to_name', 'verbose')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_rename'), ('from_name', 'axis'), ('to_name', 'copy')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_rename'), ('from_name', 'axis'), ('to_name', 'add_indicator')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_rename'), ('from_name', 'axis'), ('to_name', 'fill_value')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[REPAIR EXEC TIME]: 12.76680612564087['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 109, in <module>
    from sklearn.preprocessing import Imputer
ImportError: cannot import name 'Imputer'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.preprocessing.Imputer'), ('new_fqn', 'sklearn.impute.SimpleImputer'), ('line_no', 109)])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 111, in <module>
    imputerHumidity=SimpleImputer(missing_values='NaN',strategy='mean',axis=0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_delete'), ('from_name', 'axis'), ('to_name', '*')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'number')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'string')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'np.nan')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 115, in <module>
    imputerTemperature=SimpleImputer(missing_values='NaN',strategy='mean',axis=0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_delete'), ('from_name', 'axis'), ('to_name', '*')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 116, in <module>
    imputerTemperature=imputerTemperature.fit(temperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'number')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 116, in <module>
    imputerTemperature=imputerTemperature.fit(temperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'string')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 116, in <module>
    imputerTemperature=imputerTemperature.fit(temperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'np.nan')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 120, in <module>
    imputerappTemp=SimpleImputer(missing_values='NaN',strategy='mean',axis=0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_delete'), ('from_name', 'axis'), ('to_name', '*')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 121, in <module>
    imputerappTemp=imputerappTemp.fit(apparentTemperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'number')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 121, in <module>
    imputerappTemp=imputerappTemp.fit(apparentTemperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'string')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 121, in <module>
    imputerappTemp=imputerappTemp.fit(apparentTemperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'np.nan')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 130, in <module>
    from sklearn.cross_validation import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_validation'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.model_selection'), ('line_no', 130)])['weatherHistory.csv']
75.6339193490808


68.1090664931548


[REPAIR EXEC TIME]: 26.53103804588318['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 109, in <module>
    from sklearn.preprocessing import Imputer
ImportError: cannot import name 'Imputer'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.preprocessing.Imputer'), ('new_fqn', 'sklearn.impute.SimpleImputer'), ('line_no', 109)])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 111, in <module>
    imputerHumidity=SimpleImputer(missing_values='NaN',strategy='mean',axis=0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_delete'), ('from_name', 'axis'), ('to_name', '*')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'number')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'string')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'np.nan')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 115, in <module>
    imputerTemperature=SimpleImputer(missing_values='NaN',strategy='mean',axis=0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_delete'), ('from_name', 'axis'), ('to_name', '*')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 116, in <module>
    imputerTemperature=imputerTemperature.fit(temperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'number')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 116, in <module>
    imputerTemperature=imputerTemperature.fit(temperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'string')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 116, in <module>
    imputerTemperature=imputerTemperature.fit(temperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'np.nan')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 120, in <module>
    imputerappTemp=SimpleImputer(missing_values='NaN',strategy='mean',axis=0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_delete'), ('from_name', 'axis'), ('to_name', '*')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 121, in <module>
    imputerappTemp=imputerappTemp.fit(apparentTemperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'number')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 121, in <module>
    imputerappTemp=imputerappTemp.fit(apparentTemperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'string')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 121, in <module>
    imputerappTemp=imputerappTemp.fit(apparentTemperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'np.nan')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 130, in <module>
    from sklearn.cross_validation import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_validation'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.model_selection'), ('line_no', 130)])['weatherHistory.csv']
102.38948374387195


73.86854426685535


[REPAIR EXEC TIME]: 27.75382113456726['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 109, in <module>
    from sklearn.preprocessing import Imputer
ImportError: cannot import name 'Imputer'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.preprocessing.Imputer'), ('new_fqn', 'sklearn.impute.SimpleImputer'), ('line_no', 109)])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 111, in <module>
    imputerHumidity=SimpleImputer(missing_values='NaN',strategy='mean',axis=0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_delete'), ('from_name', 'axis'), ('to_name', '*')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'number')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'string')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 112, in <module>
    imputerHumidity=imputerHumidity.fit(humidity) 
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'np.nan')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 115, in <module>
    imputerTemperature=SimpleImputer(missing_values='NaN',strategy='mean',axis=0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_delete'), ('from_name', 'axis'), ('to_name', '*')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 116, in <module>
    imputerTemperature=imputerTemperature.fit(temperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'number')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 116, in <module>
    imputerTemperature=imputerTemperature.fit(temperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'string')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 116, in <module>
    imputerTemperature=imputerTemperature.fit(temperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'np.nan')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 120, in <module>
    imputerappTemp=SimpleImputer(missing_values='NaN',strategy='mean',axis=0)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_delete'), ('from_name', 'axis'), ('to_name', '*')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 121, in <module>
    imputerappTemp=imputerappTemp.fit(apparentTemperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'number')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 121, in <module>
    imputerappTemp=imputerappTemp.fit(apparentTemperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'string')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 121, in <module>
    imputerappTemp=imputerappTemp.fit(apparentTemperature)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
[Try Solution]: OrderedDict([('API', 'sklearn.impute.SimpleImputer'), ('action', 'arg_value_update'), ('arg_name', 'missing_values'), ('target_value', 'np.nan')])['weatherHistory.csv']
Traceback (most recent call last):
  File "simple-linear-regression-using-weatherhistory-data.py", line 130, in <module>
    from sklearn.cross_validation import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_validation'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.model_selection'), ('line_no', 130)])['weatherHistory.csv']
58.05028623841672


63.171195381103885


[REPAIR EXEC TIME]: 28.188875198364258