
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 181, in <module>
    from sklearn.cross_validation import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_validation'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.model_selection'), ('line_no', 181)])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_value_update'), ('arg_name', 'shuffle'), ('target_value', 'True')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_value_update'), ('arg_name', 'shuffle'), ('target_value', 'False')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_value_update'), ('arg_name', 'n_splits&shuffle'), ('target_value', 'True&False')])  File "logistic-regression-and-knn-predictors.py", line 233
    kf = KFold(n_splits=True), n_folds=10, shuffle=False)
                                                        ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 181, in <module>
    from sklearn.cross_validation import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_validation'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.model_selection'), ('line_no', 181)])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits'), ('to_name', 'shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits'), ('to_name', 'random_state')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_delete'), ('from_name', 'n_splits'), ('to_name', '*')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle'), ('to_name', 'n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, n_splits=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle'), ('to_name', 'random_state')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, random_state=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_delete'), ('from_name', 'shuffle'), ('to_name', '*')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'random_state'), ('to_name', 'n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'random_state'), ('to_name', 'shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_delete'), ('from_name', 'random_state'), ('to_name', '*')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&shuffle'), ('to_name', 'shuffle&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&shuffle'), ('to_name', 'shuffle&random_state')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&shuffle'), ('to_name', 'random_state&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&random_state'), ('to_name', 'shuffle&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&random_state'), ('to_name', 'random_state&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&random_state'), ('to_name', 'random_state&shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle&random_state'), ('to_name', 'n_splits&shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, n_splits=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle&random_state'), ('to_name', 'random_state&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, random_state=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle&random_state'), ('to_name', 'random_state&shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, random_state=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&shuffle&random_state'), ('to_name', 'shuffle&random_state&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&shuffle&random_state'), ('to_name', 'random_state&n_splits&shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_value_update'), ('arg_name', 'shuffle'), ('target_value', 'True')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_value_update'), ('arg_name', 'shuffle'), ('target_value', 'False')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_value_update'), ('arg_name', 'n_splits&shuffle'), ('target_value', 'True&False')])  File "logistic-regression-and-knn-predictors.py", line 233
    kf = KFold(n_splits=True), n_folds=10, shuffle=False)
                                                        ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 181, in <module>
    from sklearn.cross_validation import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_validation'
[Try Solution]: OrderedDict([('action', 'fqn'), ('old_fqn', 'sklearn.cross_validation'), ('new_fqn', 'sklearn.model_selection'), ('line_no', 181)])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits'), ('to_name', 'shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits'), ('to_name', 'random_state')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_delete'), ('from_name', 'n_splits'), ('to_name', '*')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle'), ('to_name', 'n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, n_splits=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle'), ('to_name', 'random_state')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, random_state=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_delete'), ('from_name', 'shuffle'), ('to_name', '*')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'random_state'), ('to_name', 'n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'random_state'), ('to_name', 'shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_delete'), ('from_name', 'random_state'), ('to_name', '*')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle&random_state'), ('to_name', 'n_splits&shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, n_splits=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle&random_state'), ('to_name', 'random_state&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, random_state=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'shuffle&random_state'), ('to_name', 'random_state&shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, random_state=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&shuffle'), ('to_name', 'shuffle&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&shuffle'), ('to_name', 'shuffle&random_state')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&shuffle'), ('to_name', 'random_state&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&random_state'), ('to_name', 'shuffle&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&random_state'), ('to_name', 'random_state&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&random_state'), ('to_name', 'random_state&shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&shuffle&random_state'), ('to_name', 'shuffle&random_state&n_splits')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_rename'), ('from_name', 'n_splits&shuffle&random_state'), ('to_name', 'random_state&n_splits&shuffle')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_value_update'), ('arg_name', 'shuffle'), ('target_value', 'True')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_value_update'), ('arg_name', 'shuffle'), ('target_value', 'False')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_value_update'), ('arg_name', 'shuffle&random_state'), ('target_value', 'True&False')])
Traceback (most recent call last):
  File "logistic-regression-and-knn-predictors.py", line 233, in <module>
    kf = KFold(len(catan), n_folds=10, shuffle=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
[Try Solution]: OrderedDict([('API', 'sklearn.model_selection.KFold'), ('action', 'arg_value_update'), ('arg_name', 'n_splits&shuffle'), ('target_value', 'True&False')])  File "logistic-regression-and-knn-predictors.py", line 233
    kf = KFold(n_splits=True), n_folds=10, shuffle=False)
                                                        ^
SyntaxError: invalid syntax
[REPAIR EXEC TIME]: 64.82628798484802