Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'drop'), ('target_value', 'first')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,drop="first")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'drop'), ('target_value', 'if_binary')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,drop="if_binary")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'sparse'), ('target_value', 'True')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'sparse'), ('target_value', 'False')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'handle_unknown'), ('target_value', 'error')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,handle_unknown="error")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'handle_unknown'), ('target_value', 'ignore')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,handle_unknown="ignore")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'dtype&drop'), ('target_value', 'first&if_binary')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,dtype="first")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'handle_unknown&drop'), ('target_value', 'error&ignore')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,handle_unknown="error")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'handle_unknown&drop'), ('target_value', 'first&if_binary')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,handle_unknown="first")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'drop&sparse'), ('target_value', 'first&if_binary')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,drop="first")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'drop&sparse'), ('target_value', 'True&False')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,drop=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'categories&sparse'), ('target_value', 'True&False')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,categories=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'handle_unknown&sparse'), ('target_value', 'error&ignore')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,handle_unknown="error")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'handle_unknown&sparse'), ('target_value', 'True&False')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,handle_unknown=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'dtype&sparse'), ('target_value', 'True&False')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,dtype=True)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'categories&drop'), ('target_value', 'first&if_binary')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,categories="first")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'categories&handle_unknown'), ('target_value', 'error&ignore')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,categories="error")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'dtype&handle_unknown'), ('target_value', 'error&ignore')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,dtype="error")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'dtype&drop&sparse'), ('target_value', 'first&if_binary&True')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,dtype="first")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'dtype&handle_unknown&sparse'), ('target_value', 'error&ignore&True')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,dtype="error")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'categories&drop&sparse'), ('target_value', 'first&if_binary&True')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,categories="first")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'categories&handle_unknown&sparse'), ('target_value', 'error&ignore&True')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,categories="error")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'dtype&handle_unknown&drop'), ('target_value', 'error&ignore&first')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,dtype="error")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'categories&handle_unknown&drop'), ('target_value', 'error&ignore&first')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,categories="error")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'handle_unknown&drop&sparse'), ('target_value', 'error&ignore&first')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,handle_unknown="error")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'handle_unknown&drop&sparse'), ('target_value', 'if_binary&True&False')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,handle_unknown="if_binary")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'categories&handle_unknown&drop&sparse'), ('target_value', 'error&ignore&first&if_binary')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,categories="error")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'dtype&handle_unknown&drop&sparse'), ('target_value', 'error&ignore&first&if_binary')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,dtype="error")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'categories&dtype&handle_unknown&drop'), ('target_value', 'error&ignore&first&if_binary')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,categories="error")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'categories&dtype&handle_unknown&sparse'), ('target_value', 'error&ignore&True&False')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,categories="error")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'categories&dtype&drop&sparse'), ('target_value', 'first&if_binary&True&False')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,categories="first")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_value_update'), ('arg_name', 'categories&dtype&handle_unknown&drop&sparse'), ('target_value', 'error&ignore&first&if_binary&True')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False,categories="error")
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories'), ('to_name', 'drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories'), ('to_name', 'sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories'), ('to_name', 'dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories'), ('to_name', 'handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_delete'), ('from_name', 'categories'), ('to_name', '*')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop'), ('to_name', 'categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop'), ('to_name', 'sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop'), ('to_name', 'dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop'), ('to_name', 'handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_delete'), ('from_name', 'drop'), ('to_name', '*')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'sparse'), ('to_name', 'categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , categories=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'sparse'), ('to_name', 'drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , drop=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'sparse'), ('to_name', 'dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , dtype=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'sparse'), ('to_name', 'handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , handle_unknown=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_delete'), ('from_name', 'sparse'), ('to_name', '*')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features )
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype'), ('to_name', 'categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype'), ('to_name', 'drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype'), ('to_name', 'sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype'), ('to_name', 'handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_delete'), ('from_name', 'dtype'), ('to_name', '*')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown'), ('to_name', 'categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown'), ('to_name', 'drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown'), ('to_name', 'sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown'), ('to_name', 'dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_delete'), ('from_name', 'handle_unknown'), ('to_name', '*')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop'), ('to_name', 'categories&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop'), ('to_name', 'categories&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop'), ('to_name', 'categories&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop'), ('to_name', 'handle_unknown&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop'), ('to_name', 'handle_unknown&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop'), ('to_name', 'handle_unknown&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop'), ('to_name', 'drop&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop'), ('to_name', 'drop&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop'), ('to_name', 'drop&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop'), ('to_name', 'drop&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop'), ('to_name', 'sparse&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop'), ('to_name', 'sparse&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop'), ('to_name', 'sparse&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&dtype'), ('to_name', 'dtype&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&dtype'), ('to_name', 'dtype&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&dtype'), ('to_name', 'dtype&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&dtype'), ('to_name', 'dtype&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&dtype'), ('to_name', 'handle_unknown&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&dtype'), ('to_name', 'handle_unknown&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&dtype'), ('to_name', 'handle_unknown&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&dtype'), ('to_name', 'drop&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&dtype'), ('to_name', 'drop&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&dtype'), ('to_name', 'drop&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&dtype'), ('to_name', 'sparse&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&dtype'), ('to_name', 'sparse&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&dtype'), ('to_name', 'sparse&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&drop'), ('to_name', 'categories&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&drop'), ('to_name', 'categories&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&drop'), ('to_name', 'categories&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&drop'), ('to_name', 'dtype&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&drop'), ('to_name', 'dtype&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&drop'), ('to_name', 'dtype&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&drop'), ('to_name', 'drop&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&drop'), ('to_name', 'drop&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&drop'), ('to_name', 'drop&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&drop'), ('to_name', 'drop&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&drop'), ('to_name', 'sparse&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&drop'), ('to_name', 'sparse&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&drop'), ('to_name', 'sparse&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop&sparse'), ('to_name', 'categories&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop&sparse'), ('to_name', 'categories&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop&sparse'), ('to_name', 'categories&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop&sparse'), ('to_name', 'dtype&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop&sparse'), ('to_name', 'dtype&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop&sparse'), ('to_name', 'dtype&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop&sparse'), ('to_name', 'handle_unknown&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop&sparse'), ('to_name', 'handle_unknown&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop&sparse'), ('to_name', 'handle_unknown&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop&sparse'), ('to_name', 'sparse&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop&sparse'), ('to_name', 'sparse&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop&sparse'), ('to_name', 'sparse&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'drop&sparse'), ('to_name', 'sparse&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&sparse'), ('to_name', 'dtype&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&sparse'), ('to_name', 'dtype&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&sparse'), ('to_name', 'dtype&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&sparse'), ('to_name', 'handle_unknown&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&sparse'), ('to_name', 'handle_unknown&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&sparse'), ('to_name', 'handle_unknown&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&sparse'), ('to_name', 'drop&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&sparse'), ('to_name', 'drop&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&sparse'), ('to_name', 'drop&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&sparse'), ('to_name', 'sparse&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&sparse'), ('to_name', 'sparse&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&sparse'), ('to_name', 'sparse&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&sparse'), ('to_name', 'sparse&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&sparse'), ('to_name', 'categories&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&sparse'), ('to_name', 'categories&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&sparse'), ('to_name', 'categories&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&sparse'), ('to_name', 'dtype&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&sparse'), ('to_name', 'dtype&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&sparse'), ('to_name', 'dtype&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&sparse'), ('to_name', 'drop&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&sparse'), ('to_name', 'drop&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&sparse'), ('to_name', 'drop&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&sparse'), ('to_name', 'sparse&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&sparse'), ('to_name', 'sparse&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&sparse'), ('to_name', 'sparse&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'handle_unknown&sparse'), ('to_name', 'sparse&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&sparse'), ('to_name', 'categories&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&sparse'), ('to_name', 'categories&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&sparse'), ('to_name', 'categories&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&sparse'), ('to_name', 'handle_unknown&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&sparse'), ('to_name', 'handle_unknown&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&sparse'), ('to_name', 'handle_unknown&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&sparse'), ('to_name', 'drop&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&sparse'), ('to_name', 'drop&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&sparse'), ('to_name', 'drop&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&sparse'), ('to_name', 'sparse&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&sparse'), ('to_name', 'sparse&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&sparse'), ('to_name', 'sparse&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&sparse'), ('to_name', 'sparse&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&drop'), ('to_name', 'dtype&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&drop'), ('to_name', 'dtype&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&drop'), ('to_name', 'dtype&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&drop'), ('to_name', 'handle_unknown&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&drop'), ('to_name', 'handle_unknown&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&drop'), ('to_name', 'handle_unknown&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&drop'), ('to_name', 'drop&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&drop'), ('to_name', 'drop&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&drop'), ('to_name', 'drop&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&drop'), ('to_name', 'drop&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&drop'), ('to_name', 'sparse&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&drop'), ('to_name', 'sparse&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&drop'), ('to_name', 'sparse&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&handle_unknown'), ('to_name', 'dtype&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&handle_unknown'), ('to_name', 'dtype&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&handle_unknown'), ('to_name', 'dtype&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&handle_unknown'), ('to_name', 'handle_unknown&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&handle_unknown'), ('to_name', 'handle_unknown&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&handle_unknown'), ('to_name', 'handle_unknown&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&handle_unknown'), ('to_name', 'handle_unknown&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&handle_unknown'), ('to_name', 'drop&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&handle_unknown'), ('to_name', 'drop&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&handle_unknown'), ('to_name', 'drop&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&handle_unknown'), ('to_name', 'sparse&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&handle_unknown'), ('to_name', 'sparse&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'categories&handle_unknown'), ('to_name', 'sparse&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&handle_unknown'), ('to_name', 'categories&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&handle_unknown'), ('to_name', 'categories&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&handle_unknown'), ('to_name', 'categories&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&handle_unknown'), ('to_name', 'handle_unknown&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&handle_unknown'), ('to_name', 'handle_unknown&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&handle_unknown'), ('to_name', 'handle_unknown&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&handle_unknown'), ('to_name', 'handle_unknown&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&handle_unknown'), ('to_name', 'drop&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&handle_unknown'), ('to_name', 'drop&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&handle_unknown'), ('to_name', 'drop&sparse')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&handle_unknown'), ('to_name', 'sparse&categories')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&handle_unknown'), ('to_name', 'sparse&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&handle_unknown'), ('to_name', 'sparse&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop&sparse'), ('to_name', 'categories&dtype&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop&sparse'), ('to_name', 'categories&dtype&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop&sparse'), ('to_name', 'categories&handle_unknown&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop&sparse'), ('to_name', 'categories&handle_unknown&drop')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop&sparse'), ('to_name', 'categories&sparse&dtype')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop&sparse'), ('to_name', 'categories&sparse&handle_unknown')])Null Values in age : 0
Null Values in sex : 0
Null Values in bmi : 0
Null Values in children : 0
Null Values in smoker : 0
Null Values in region : 0
Null Values in charges : 0


Traceback (most recent call last):
  File "patient-charges-regression-and-classification.py", line 228, in <module>
    ohe = OneHotEncoder(categorical_features=categorical_features , sparse=False)
  File "/home/cgzhu/anaconda3/envs/migration-plus/lib/python3.6/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'
[Try Solution]: OrderedDict([('API', 'sklearn.preprocessing.OneHotEncoder'), ('action', 'arg_rename'), ('from_name', 'dtype&drop&sparse'), ('to_name', 'categories&sparse&drop')])